import mock from "../mock";

const tradeshowDB = {
  majorCategory_lineCodes: [
    {
      lineCode: "477",
      description: "20/10",
      lineGroup: 9,
      id: 1832,
    },
    {
      lineCode: "46N",
      description: "3M / BONDO FILLERS",
      lineGroup: 2,
      id: 518,
    },
    {
      lineCode: "14P",
      description: "3M AEARO PELTOR",
      lineGroup: 2,
      id: 404,
    },
    {
      lineCode: "195",
      description: "3M AUTOMOTIVE",
      lineGroup: 2,
      id: 405,
    },
    {
      lineCode: "3MI",
      description: "3M INDUSTRIAL",
      lineGroup: 2,
      id: 406,
    },
    {
      lineCode: "68E",
      description: "AC DELCO ADV BRGS & SEALS",
      lineGroup: 19,
      id: 111,
    },
    {
      lineCode: "67C",
      description: "AC DELCO ADV CHASSIS",
      lineGroup: 19,
      id: 153,
    },
    {
      lineCode: "67K",
      description: "AC DELCO ADV CONTROL ARMS",
      lineGroup: 19,
      id: 154,
    },
    {
      lineCode: "67N",
      description: "AC DELCO ADV FRICTION",
      lineGroup: 19,
      id: 149,
    },
    {
      lineCode: "67V",
      description: "AC DELCO ADV ROTORS",
      lineGroup: 19,
      id: 159,
    },
    {
      lineCode: "67F",
      description: "AC DELCO AIR FILTERS",
      lineGroup: 19,
      id: 130,
    },
    {
      lineCode: "69S",
      description: "AC DELCO ALT & STARTERS",
      lineGroup: 19,
      id: 165,
    },
    {
      lineCode: "67X",
      description: "AC DELCO ANTIFREEZE",
      lineGroup: 19,
      id: 162,
    },
    {
      lineCode: "192",
      description: "AC DELCO BATTERIES",
      lineGroup: 19,
      id: 141,
    },
    {
      lineCode: "68F",
      description: "AC DELCO BEAR/SEALS",
      lineGroup: 19,
      id: 112,
    },
    {
      lineCode: "68Z",
      description: "AC DELCO BELTS/HOSES",
      lineGroup: 19,
      id: 156,
    },
    {
      lineCode: "68I",
      description: "AC DELCO CAPS/THERMS",
      lineGroup: 19,
      id: 113,
    },
    {
      lineCode: "69K",
      description: "AC DELCO CHEMICALS",
      lineGroup: 19,
      id: 135,
    },
    {
      lineCode: "07D",
      description: "AC DELCO DEF (DIESEL EXHAUST FLUID)",
      lineGroup: 19,
      id: 140,
    },
    {
      lineCode: "69E",
      description: "AC DELCO EMISSION PARTS",
      lineGroup: 19,
      id: 120,
    },
    {
      lineCode: "69F",
      description: "AC DELCO FUEL PUMPS",
      lineGroup: 19,
      id: 121,
    },
    {
      lineCode: "69J",
      description: "AC DELCO FWD PARTS",
      lineGroup: 19,
      id: 123,
    },
    {
      lineCode: "69G",
      description: "AC DELCO GAS FILTERS",
      lineGroup: 19,
      id: 134,
    },
    {
      lineCode: "69I",
      description: "AC DELCO IGNITION",
      lineGroup: 19,
      id: 122,
    },
    {
      lineCode: "68N",
      description: "AC DELCO NEW ALT & STARTERS",
      lineGroup: 19,
      id: 164,
    },
    {
      lineCode: "69P",
      description: "AC DELCO O2 SENSORS",
      lineGroup: 19,
      id: 125,
    },
    {
      lineCode: "68O",
      description: "AC DELCO OE BRAKES",
      lineGroup: 19,
      id: 115,
    },
    {
      lineCode: "67O",
      description: "AC DELCO OIL",
      lineGroup: 19,
      id: 161,
    },
    {
      lineCode: "69O",
      description: "AC DELCO OIL FILTERS",
      lineGroup: 19,
      id: 137,
    },
    {
      lineCode: "69D",
      description: "AC DELCO PROFESSIONAL BRAKES",
      lineGroup: 19,
      id: 152,
    },
    {
      lineCode: "69C",
      description: "AC DELCO PROFESSIONAL CALIPERS",
      lineGroup: 19,
      id: 151,
    },
    {
      lineCode: "67J",
      description: "AC DELCO PROFESSIONAL CHASSIS",
      lineGroup: 19,
      id: 157,
    },
    {
      lineCode: "67U",
      description: "AC DELCO PROFESSIONAL U-JOINTS",
      lineGroup: 19,
      id: 158,
    },
    {
      lineCode: "237",
      description: "AC DELCO SPARK PLUGS",
      lineGroup: 19,
      id: 107,
    },
    {
      lineCode: "67I",
      description: "AC DELCO TIMING BELTS",
      lineGroup: 19,
      id: 155,
    },
    {
      lineCode: "68U",
      description: "AC DELCO WATER PUMPS",
      lineGroup: 19,
      id: 133,
    },
    {
      lineCode: "69X",
      description: "AC DELCO WIRE & CABLE",
      lineGroup: 19,
      id: 129,
    },
    {
      lineCode: "003",
      description: "ACCEL",
      lineGroup: 4,
      id: 635,
    },
    {
      lineCode: "294",
      description: "ACCURATE TRANSMISSION",
      lineGroup: 1,
      id: 1456,
    },
    {
      lineCode: "0AA",
      description: "ACTION ACCESSORIES",
      lineGroup: 4,
      id: 2667,
    },
    {
      lineCode: "51I",
      description: "AEM INDUCTION",
      lineGroup: 4,
      id: 740,
    },
    {
      lineCode: "6BL",
      description: "AGS BRAKE LINES",
      lineGroup: 1,
      id: 553,
    },
    {
      lineCode: "004",
      description: "AIMCO DRUMS & ROTORS",
      lineGroup: 1,
      id: 1686,
    },
    {
      lineCode: "AIR",
      description: "AIR LIFT AIR SPRINGS",
      lineGroup: 4,
      id: 2675,
    },
    {
      lineCode: "765",
      description: "AIRAWARE/SCHRADER-BRIDGEPORT",
      lineGroup: 10,
      id: 850,
    },
    {
      lineCode: "ALK",
      description: "AL-KO AXIS",
      lineGroup: 14,
      id: 2676,
    },
    {
      lineCode: "936",
      description: "ALEMITE",
      lineGroup: 5,
      id: 724,
    },
    {
      lineCode: "547",
      description: "ALLDEC TRADING",
      lineGroup: 2,
      id: 1931,
    },
    {
      lineCode: "006",
      description: "AMERICAN GREASE STICK",
      lineGroup: 9,
      id: 552,
    },
    {
      lineCode: "AMP",
      description: "AMP RESEARCH",
      lineGroup: 4,
      id: 2678,
    },
    {
      lineCode: "62M",
      description: "ANCHOR MOTOR MOUNTS",
      lineGroup: 1,
      id: 2070,
    },
    {
      lineCode: "243",
      description: "ANTIFREEZE",
      lineGroup: 9,
      id: 430,
    },
    {
      lineCode: "ANZ",
      description: "ANZO USA",
      lineGroup: 4,
      id: 2680,
    },
    {
      lineCode: "250",
      description: "ARMORALL CHEMICALS",
      lineGroup: 9,
      id: 809,
    },
    {
      lineCode: "913",
      description: "ARP (AUTOMOTIVE RACING PRODUCTS)",
      lineGroup: 21,
      id: 2493,
    },
    {
      lineCode: "34A",
      description: "ASSENMACHER TOOLS",
      lineGroup: 7,
      id: 1569,
    },
    {
      lineCode: "ATK",
      description: "ATK ENGINES",
      lineGroup: 21,
      id: 877,
    },
    {
      lineCode: "122",
      description: "AUTO METER GAUGES",
      lineGroup: 4,
      id: 473,
    },
    {
      lineCode: "206",
      description: "AUTO VENT SHADE",
      lineGroup: 4,
      id: 761,
    },
    {
      lineCode: "9FI",
      description: "AUTOLINE FUEL INJECTION",
      lineGroup: 1,
      id: 350,
    },
    {
      lineCode: "011",
      description: "AUTOLITE SPARK PLUGS",
      lineGroup: 1,
      id: 464,
    },
    {
      lineCode: "11X",
      description: "AUTOLITE XTREME PLUGS",
      lineGroup: 1,
      id: 466,
    },
    {
      lineCode: "22E",
      description: "AUTOMETER TEST EQUIPMENT",
      lineGroup: 5,
      id: 475,
    },
    {
      lineCode: "514",
      description: "B & M RACING",
      lineGroup: 4,
      id: 1895,
    },
    {
      lineCode: "BAK",
      description: "BAK INDUSTRIES",
      lineGroup: 4,
      id: 554,
    },
    {
      lineCode: "400",
      description: "BALDWIN FILTER",
      lineGroup: 1,
      id: 884,
    },
    {
      lineCode: "BAR",
      description: "BARTEC TPMS TOOLS",
      lineGroup: 5,
      id: 2717,
    },
    {
      lineCode: "BAS",
      description: "BASECAMP",
      lineGroup: 14,
      id: 845,
    },
    {
      lineCode: "12K",
      description: "BBK PERFORMANCE",
      lineGroup: 4,
      id: 1078,
    },
    {
      lineCode: "BAF",
      description: "BECK ANTIFREEZE",
      lineGroup: 22,
      id: 166,
    },
    {
      lineCode: "BCH",
      description: "BECK CHASSIS",
      lineGroup: 22,
      id: 169,
    },
    {
      lineCode: "BCR",
      description: "BECK CONTROL ARMS",
      lineGroup: 22,
      id: 171,
    },
    {
      lineCode: "BDR",
      description: "BECK DRUMS & ROTORS",
      lineGroup: 22,
      id: 174,
    },
    {
      lineCode: "BFI",
      description: "BECK FILTERS",
      lineGroup: 22,
      id: 178,
    },
    {
      lineCode: "BFR",
      description: "BECK FRICTION",
      lineGroup: 22,
      id: 182,
    },
    {
      lineCode: "BFO",
      description: "BECK FRICTION OE",
      lineGroup: 22,
      id: 180,
    },
    {
      lineCode: "BIG",
      description: "BECK IGNITION",
      lineGroup: 22,
      id: 186,
    },
    {
      lineCode: "BNW",
      description: "BECK NEW W/PUMP",
      lineGroup: 22,
      id: 191,
    },
    {
      lineCode: "BOI",
      description: "BECK OIL",
      lineGroup: 22,
      id: 192,
    },
    {
      lineCode: "RUG",
      description: "BEDRUG BED LINERS",
      lineGroup: 4,
      id: 3080,
    },
    {
      lineCode: "954",
      description: "BELL TECH",
      lineGroup: 4,
      id: 776,
    },
    {
      lineCode: "0BC",
      description: "BIG COUNTRY",
      lineGroup: 4,
      id: 943,
    },
    {
      lineCode: "0BM",
      description: "BLUE MAGIC",
      lineGroup: 2,
      id: 2727,
    },
    {
      lineCode: "BWR",
      description: "BLUE STREAK REMAN",
      lineGroup: 1,
      id: 731,
    },
    {
      lineCode: "BLT",
      description: "BOLT",
      lineGroup: 4,
      id: 2726,
    },
    {
      lineCode: "460",
      description: "BONDO / MARHYDE",
      lineGroup: 2,
      id: 517,
    },
    {
      lineCode: "BWE",
      description: "BORG EMISSION",
      lineGroup: 1,
      id: 388,
    },
    {
      lineCode: "BWI",
      description: "BORG IGNITION",
      lineGroup: 1,
      id: 390,
    },
    {
      lineCode: "BWS",
      description: "BORG TPMS",
      lineGroup: 1,
      id: 392,
    },
    {
      lineCode: "BWT",
      description: "BORG WARNER TECHSMART",
      lineGroup: 1,
      id: 393,
    },
    {
      lineCode: "79F",
      description: "BOSCH FILTERS",
      lineGroup: 1,
      id: 256,
    },
    {
      lineCode: "379",
      description: "BOSCH FUEL & IGNITION",
      lineGroup: 1,
      id: 251,
    },
    {
      lineCode: "79U",
      description: "BOSCH FUEL PUMPS",
      lineGroup: 1,
      id: 262,
    },
    {
      lineCode: "79N",
      description: "BOSCH NEW ALTERNATORS & STARTERS",
      lineGroup: 1,
      id: 258,
    },
    {
      lineCode: "79O",
      description: "BOSCH OXY SENSORS",
      lineGroup: 1,
      id: 259,
    },
    {
      lineCode: "79A",
      description: "BOSCH REMAN ELECTRICAL",
      lineGroup: 1,
      id: 253,
    },
    {
      lineCode: "380",
      description: "BOSCH SPARK PLUGS",
      lineGroup: 1,
      id: 252,
    },
    {
      lineCode: "79W",
      description: "BOSCH WIPER PRODUCTS",
      lineGroup: 1,
      id: 263,
    },
    {
      lineCode: "79X",
      description: "BOSCH WIRES",
      lineGroup: 1,
      id: 264,
    },
    {
      lineCode: "166",
      description: "BOSS FLASHLIGHT & MAGLITE",
      lineGroup: 7,
      id: 265,
    },
    {
      lineCode: "BRI",
      description: "BRIGHTSOURCE HID",
      lineGroup: 4,
      id: 2729,
    },
    {
      lineCode: "73R",
      description: "BULLY DOG BIG RIG",
      lineGroup: 4,
      id: 535,
    },
    {
      lineCode: "73B",
      description: "BULLY DOG TECHNOLOGIES",
      lineGroup: 4,
      id: 534,
    },
    {
      lineCode: "0BF",
      description: "BUNGEE FLAG",
      lineGroup: 3,
      id: 2721,
    },
    {
      lineCode: "26B",
      description: "BUSHWACKER",
      lineGroup: 4,
      id: 1404,
    },
    {
      lineCode: "37B",
      description: "BUSSMANN FUSES",
      lineGroup: 1,
      id: 1630,
    },
    {
      lineCode: "49C",
      description: "CAMCO RV PRODUCTS",
      lineGroup: 14,
      id: 1866,
    },
    {
      lineCode: "137",
      description: "CAR-FRESHNER",
      lineGroup: 10,
      id: 1095,
    },
    {
      lineCode: "53C",
      description: "CARDONE CALIPER",
      lineGroup: 1,
      id: 222,
    },
    {
      lineCode: "53D",
      description: "CARDONE DISTRIBUTOR",
      lineGroup: 1,
      id: 203,
    },
    {
      lineCode: "53X",
      description: "CARDONE NEW SHAFTS",
      lineGroup: 1,
      id: 214,
    },
    {
      lineCode: "54N",
      description: "CARDONE NEW WATER PUMPS",
      lineGroup: 1,
      id: 219,
    },
    {
      lineCode: "53Y",
      description: "CARDONE NEW WINDOW MOTORS",
      lineGroup: 1,
      id: 215,
    },
    {
      lineCode: "53B",
      description: "CARDONE P/B BOOSTER",
      lineGroup: 1,
      id: 202,
    },
    {
      lineCode: "53P",
      description: "CARDONE POWER STEERING",
      lineGroup: 1,
      id: 227,
    },
    {
      lineCode: "53R",
      description: "CARDONE RACK & PINION",
      lineGroup: 1,
      id: 209,
    },
    {
      lineCode: "53S",
      description: "CARDONE SMOG PUMP",
      lineGroup: 1,
      id: 210,
    },
    {
      lineCode: "54H",
      description: "CARDONE WINDOW & TG MOTORS/GEARS",
      lineGroup: 1,
      id: 217,
    },
    {
      lineCode: "54E",
      description: "CARDONE WIPER MOTORS/PULSE BOARDS",
      lineGroup: 1,
      id: 216,
    },
    {
      lineCode: "247",
      description: "CASTROL OIL",
      lineGroup: 6,
      id: 443,
    },
    {
      lineCode: "CSC",
      description: "CASTROL SUPER CLEAN",
      lineGroup: 9,
      id: 446,
    },
    {
      lineCode: "36C",
      description: "CENTRAL TOOL & STORM",
      lineGroup: 7,
      id: 1611,
    },
    {
      lineCode: "211",
      description: "CHAMPION SPARK PLUGS",
      lineGroup: 1,
      id: 1302,
    },
    {
      lineCode: "25G",
      description: "CHEMAC / BRITELAND",
      lineGroup: 9,
      id: 1385,
    },
    {
      lineCode: "67H",
      description: "CHEVRON OIL",
      lineGroup: 6,
      id: 539,
    },
    {
      lineCode: "270",
      description: "CHICAGO PNEUMATIC",
      lineGroup: 7,
      id: 558,
    },
    {
      lineCode: "CPC",
      description: "CHICAGO PNEUMATIC COMPRESSORS",
      lineGroup: 5,
      id: 559,
    },
    {
      lineCode: "38C",
      description: "CHROMA GRAPHIC DETAILS",
      lineGroup: 10,
      id: 989,
    },
    {
      lineCode: "71C",
      description: "CIPA MIRRORS",
      lineGroup: 14,
      id: 2186,
    },
    {
      lineCode: "CLA",
      description: "CLASSIC ACCESSORIES",
      lineGroup: 14,
      id: 2798,
    },
    {
      lineCode: "140",
      description: "CLEVITE/AE ENGINE PARTS",
      lineGroup: 21,
      id: 316,
    },
    {
      lineCode: "174",
      description: "CLIPLIGHT",
      lineGroup: 7,
      id: 904,
    },
    {
      lineCode: "932",
      description: "CLOYES GEAR",
      lineGroup: 21,
      id: 2797,
    },
    {
      lineCode: "359",
      description: "COATS EQUIPMENT",
      lineGroup: 5,
      id: 831,
    },
    {
      lineCode: "COC",
      description: "COCO ABSORBANTS",
      lineGroup: 3,
      id: 2803,
    },
    {
      lineCode: "329",
      description: "COLE HERSEE",
      lineGroup: 3,
      id: 655,
    },
    {
      lineCode: "CGI",
      description: "COMETIC GASKET INC",
      lineGroup: 21,
      id: 2793,
    },
    {
      lineCode: "245",
      description: "COMP CAMS",
      lineGroup: 21,
      id: 519,
    },
    {
      lineCode: "CCO",
      description: "COMP CAMS OIL",
      lineGroup: 6,
      id: 520,
    },
    {
      lineCode: "763",
      description: "COMPETITION ENGINEERING",
      lineGroup: 4,
      id: 898,
    },
    {
      lineCode: "CRP",
      description: "CONTINENTAL BELTS",
      lineGroup: 24,
      id: 99,
    },
    {
      lineCode: "CTP",
      description: "CONTITECH TIMING PRODUCTS",
      lineGroup: 24,
      id: 463,
    },
    {
      lineCode: "334",
      description: "COVERCRAFT",
      lineGroup: 4,
      id: 1547,
    },
    {
      lineCode: "CPS",
      description: "CPS REFRIG EQUIPMENT",
      lineGroup: 5,
      id: 908,
    },
    {
      lineCode: "510",
      description: "CRC CHEMICALS",
      lineGroup: 9,
      id: 1893,
    },
    {
      lineCode: "310",
      description: "CRESCENT TOOLS",
      lineGroup: 7,
      id: 338,
    },
    {
      lineCode: "0CA",
      description: "CRUISER ACCESSORIES",
      lineGroup: 10,
      id: 889,
    },
    {
      lineCode: "CTK",
      description: "CTEK CHARGERS",
      lineGroup: 4,
      id: 2808,
    },
    {
      lineCode: "CHA",
      description: "CURT HITCH ACCESSORIES",
      lineGroup: 14,
      id: 542,
    },
    {
      lineCode: "099",
      description: "CYCLE WIPERS",
      lineGroup: 3,
      id: 2596,
    },
    {
      lineCode: "395",
      description: "DAFCO FILTRATION",
      lineGroup: 2,
      id: 1660,
    },
    {
      lineCode: "049",
      description: "DAYCO AUTOMOTIVE",
      lineGroup: 1,
      id: 394,
    },
    {
      lineCode: "49E",
      description: "DAYCO BELT STICKS",
      lineGroup: 1,
      id: 396,
    },
    {
      lineCode: "49S",
      description: "DAYCO SNOWMOBILE BELTS",
      lineGroup: 14,
      id: 398,
    },
    {
      lineCode: "49T",
      description: "DAYCO TIMING BELTS",
      lineGroup: 1,
      id: 399,
    },
    {
      lineCode: "49K",
      description: "DAYCO TIMING KITS",
      lineGroup: 1,
      id: 397,
    },
    {
      lineCode: "417",
      description: "DEE ZEE",
      lineGroup: 4,
      id: 563,
    },
    {
      lineCode: "DEG",
      description: "DEGIL SAFETY PRODUCTS",
      lineGroup: 2,
      id: 2830,
    },
    {
      lineCode: "52D",
      description: "DEI (DESIGN ENGINEERING)",
      lineGroup: 4,
      id: 1914,
    },
    {
      lineCode: "ACD",
      description: "DELCO ADVANTAGE BATTERIES",
      lineGroup: 19,
      id: 147,
    },
    {
      lineCode: "047",
      description: "DETAILER'S CHOICE",
      lineGroup: 10,
      id: 837,
    },
    {
      lineCode: "47D",
      description: "DEVILBISS & BINKS & CAMAIR",
      lineGroup: 2,
      id: 1835,
    },
    {
      lineCode: "26D",
      description: "DIABLOSPORT",
      lineGroup: 4,
      id: 500,
    },
    {
      lineCode: "0DF",
      description: "DIESEL EXHAUST FLUID",
      lineGroup: 9,
      id: 433,
    },
    {
      lineCode: "050",
      description: "DL HANDCLEANER",
      lineGroup: 9,
      id: 710,
    },
    {
      lineCode: "051",
      description: "DOCAP",
      lineGroup: 3,
      id: 656,
    },
    {
      lineCode: "DOM",
      description: "DOMETIC",
      lineGroup: 14,
      id: 2836,
    },
    {
      lineCode: "321",
      description: "DOMINION SURE SEAL",
      lineGroup: 2,
      id: 1525,
    },
    {
      lineCode: "286",
      description: "DORMAN HELP",
      lineGroup: 10,
      id: 292,
    },
    {
      lineCode: "28M",
      description: "DORMAN MANIFOLDS",
      lineGroup: 21,
      id: 295,
    },
    {
      lineCode: "28Z",
      description: "DORMAN OE SOLUTIONS",
      lineGroup: 1,
      id: 299,
    },
    {
      lineCode: "28O",
      description: "DORMAN OIL LINES",
      lineGroup: 1,
      id: 296,
    },
    {
      lineCode: "16A",
      description: "DUPLICOLOR",
      lineGroup: 2,
      id: 529,
    },
    {
      lineCode: "14A",
      description: "DURA LUBE",
      lineGroup: 9,
      id: 1126,
    },
    {
      lineCode: "17D",
      description: "DURA-BOND ENGINE BEARINGS",
      lineGroup: 21,
      id: 1186,
    },
    {
      lineCode: "453",
      description: "DV SYSTEMS",
      lineGroup: 5,
      id: 1795,
    },
    {
      lineCode: "42D",
      description: "DYNABRADE AIR TOOLS",
      lineGroup: 2,
      id: 1742,
    },
    {
      lineCode: "30D",
      description: "DYNAMAT",
      lineGroup: 4,
      id: 716,
    },
    {
      lineCode: "32E",
      description: "E-Z MIX",
      lineGroup: 2,
      id: 1532,
    },
    {
      lineCode: "997",
      description: "E-Z RECT / HI-CUBE",
      lineGroup: 11,
      id: 938,
    },
    {
      lineCode: "33E",
      description: "EAGLE COMPRESSOR",
      lineGroup: 5,
      id: 1552,
    },
    {
      lineCode: "ECO",
      description: "ECO-LED",
      lineGroup: 14,
      id: 590,
    },
    {
      lineCode: "296",
      description: "EDELBROCK",
      lineGroup: 4,
      id: 480,
    },
    {
      lineCode: "66E",
      description: "ELGIN ENGINE PARTS",
      lineGroup: 21,
      id: 2118,
    },
    {
      lineCode: "EMZ",
      description: "EMZONE REFRIGERANTS",
      lineGroup: 9,
      id: 2846,
    },
    {
      lineCode: "383",
      description: "EQUUS INNOVA TEST EQUIP",
      lineGroup: 7,
      id: 1641,
    },
    {
      lineCode: "354",
      description: "ERICKSON STRAPS & TIE DOWNS",
      lineGroup: 14,
      id: 1586,
    },
    {
      lineCode: "19E",
      description: "ESCORT RADAR DETECTORS",
      lineGroup: 4,
      id: 823,
    },
    {
      lineCode: "60Q",
      description: "EUROVAC EQUIPMENT",
      lineGroup: 5,
      id: 566,
    },
    {
      lineCode: "0EX",
      description: "EXTANG",
      lineGroup: 4,
      id: 543,
    },
    {
      lineCode: "EXT",
      description: "EXTRACTOR",
      lineGroup: 7,
      id: 827,
    },
    {
      lineCode: "38F",
      description: "FARECLA POLISH",
      lineGroup: 2,
      id: 925,
    },
    {
      lineCode: "FST",
      description: "FAST/FUEL-AIR-SPARK-TECHNOLOGY",
      lineGroup: 21,
      id: 704,
    },
    {
      lineCode: "FWT",
      description: "FASTWAY TRAILER",
      lineGroup: 14,
      id: 2865,
    },
    {
      lineCode: "848",
      description: "FBS",
      lineGroup: 2,
      id: 2397,
    },
    {
      lineCode: "557",
      description: "FEL-PRO",
      lineGroup: 21,
      id: 1946,
    },
    {
      lineCode: "947",
      description: "FIA INTERIOR DESIGN",
      lineGroup: 4,
      id: 2529,
    },
    {
      lineCode: "340",
      description: "FIBREGLASS EVERCOAT",
      lineGroup: 2,
      id: 1564,
    },
    {
      lineCode: "49F",
      description: "FIRESTONE AIR BAGS",
      lineGroup: 14,
      id: 1867,
    },
    {
      lineCode: "FLA",
      description: "FLAMING RIVER",
      lineGroup: 4,
      id: 2856,
    },
    {
      lineCode: "346",
      description: "FLEX-A-LITE",
      lineGroup: 4,
      id: 1566,
    },
    {
      lineCode: "507",
      description: "FLOOR DRY (CANDRY)",
      lineGroup: 3,
      id: 1883,
    },
    {
      lineCode: "104",
      description: "FLOOR DRY (MERCATOR)",
      lineGroup: 3,
      id: 1022,
    },
    {
      lineCode: "42A",
      description: "FLOW-TECH",
      lineGroup: 4,
      id: 1739,
    },
    {
      lineCode: "37A",
      description: "FLOWMASTER",
      lineGroup: 4,
      id: 1629,
    },
    {
      lineCode: "804",
      description: "FOUR SEASONS",
      lineGroup: 1,
      id: 670,
    },
    {
      lineCode: "063",
      description: "FRAM AUTOMOTIVE",
      lineGroup: 1,
      id: 416,
    },
    {
      lineCode: "538",
      description: "FRAM HEAVY DUTY",
      lineGroup: 1,
      id: 415,
    },
    {
      lineCode: "63T",
      description: "FRAM TOUGH GUARD",
      lineGroup: 1,
      id: 417,
    },
    {
      lineCode: "63X",
      description: "FRAM ULTRA FILTERS",
      lineGroup: 1,
      id: 418,
    },
    {
      lineCode: "FXE",
      description: "FX EXHAUST",
      lineGroup: 1,
      id: 2866,
    },
    {
      lineCode: "420",
      description: "G HJUKSTROM",
      lineGroup: 7,
      id: 1732,
    },
    {
      lineCode: "499",
      description: "G-FORCE RACING GEAR",
      lineGroup: 4,
      id: 1864,
    },
    {
      lineCode: "G2E",
      description: "G2S EQUIPMENT",
      lineGroup: 5,
      id: 426,
    },
    {
      lineCode: "G2S",
      description: "G2S TOOLS",
      lineGroup: 7,
      id: 428,
    },
    {
      lineCode: "0GB",
      description: "GARBAGE BAGS",
      lineGroup: 3,
      id: 891,
    },
    {
      lineCode: "772",
      description: "GATES MISC",
      lineGroup: 1,
      id: 420,
    },
    {
      lineCode: "12G",
      description: "GE AUTOMOTIVE BULBS",
      lineGroup: 1,
      id: 483,
    },
    {
      lineCode: "12H",
      description: "GE HOUSEHOLD & SHOP BULBS",
      lineGroup: 3,
      id: 484,
    },
    {
      lineCode: "121",
      description: "GENO - AUVECO FASTENERS",
      lineGroup: 2,
      id: 1069,
    },
    {
      lineCode: "0GO",
      description: "GO RHINO",
      lineGroup: 4,
      id: 944,
    },
    {
      lineCode: "179",
      description: "GOJO HAND CLEANER",
      lineGroup: 9,
      id: 1184,
    },
    {
      lineCode: "457",
      description: "GOLD EAGLE-303 PROTECTANT",
      lineGroup: 9,
      id: 1797,
    },
    {
      lineCode: "785",
      description: "GORILLA NUTS",
      lineGroup: 4,
      id: 2305,
    },
    {
      lineCode: "GPI",
      description: "GREAT PLAINS INDUSTRIES",
      lineGroup: 3,
      id: 2879,
    },
    {
      lineCode: "218",
      description: "GREEN LINE HOSE & FITTINGS",
      lineGroup: 3,
      id: 485,
    },
    {
      lineCode: "065",
      description: "GROTE",
      lineGroup: 1,
      id: 929,
    },
    {
      lineCode: "GTC",
      description: "GTC TEST EQUIPMENT",
      lineGroup: 7,
      id: 2882,
    },
    {
      lineCode: "066",
      description: "HASTINGS GAUGES TOOLS",
      lineGroup: 7,
      id: 331,
    },
    {
      lineCode: "66H",
      description: "HASTINGS RACING RINGS",
      lineGroup: 21,
      id: 528,
    },
    {
      lineCode: "66A",
      description: "HASTINGS RINGS",
      lineGroup: 21,
      id: 527,
    },
    {
      lineCode: "209",
      description: "HAYDEN FAN CLUTCH",
      lineGroup: 1,
      id: 931,
    },
    {
      lineCode: "443",
      description: "HAYNES BOOKS",
      lineGroup: 10,
      id: 1773,
    },
    {
      lineCode: "519",
      description: "HEDMAN STREET HEDDERS",
      lineGroup: 4,
      id: 1013,
    },
    {
      lineCode: "411",
      description: "HELICOIL",
      lineGroup: 7,
      id: 1712,
    },
    {
      lineCode: "424",
      description: "HELLA",
      lineGroup: 10,
      id: 469,
    },
    {
      lineCode: "15H",
      description: "HI-LIFT JACKS",
      lineGroup: 7,
      id: 1150,
    },
    {
      lineCode: "HEP",
      description: "HITACHI EMISSION PARTS",
      lineGroup: 24,
      id: 280,
    },
    {
      lineCode: "HFJ",
      description: "HITACHI FUEL INJECTORS",
      lineGroup: 24,
      id: 281,
    },
    {
      lineCode: "HFP",
      description: "HITACHI FUEL PUMPS",
      lineGroup: 24,
      id: 282,
    },
    {
      lineCode: "HIC",
      description: "HITACHI IGNITION COILS",
      lineGroup: 24,
      id: 283,
    },
    {
      lineCode: "HMA",
      description: "HITACHI MASS AIR FLOW",
      lineGroup: 24,
      id: 284,
    },
    {
      lineCode: "HSE",
      description: "HITACHI SENSORS",
      lineGroup: 24,
      id: 289,
    },
    {
      lineCode: "HWP",
      description: "HITACHI WATER PUMPS",
      lineGroup: 24,
      id: 291,
    },
    {
      lineCode: "070",
      description: "HOLLEY",
      lineGroup: 4,
      id: 2161,
    },
    {
      lineCode: "483",
      description: "HONEYWELL SAFETY PRODUCTS",
      lineGroup: 2,
      id: 980,
    },
    {
      lineCode: "HOP",
      description: "HOPKINS MANUFACTURING",
      lineGroup: 3,
      id: 839,
    },
    {
      lineCode: "0HL",
      description: "HOWARD LEIGHT-USE 483",
      lineGroup: 2,
      id: 981,
    },
    {
      lineCode: "07H",
      description: "HOWARDS CAMS",
      lineGroup: 21,
      id: 2331,
    },
    {
      lineCode: "52H",
      description: "HOWES LUBRICANTS",
      lineGroup: 9,
      id: 874,
    },
    {
      lineCode: "60B",
      description: "HUNTER ENGINEERING CO",
      lineGroup: 5,
      id: 1008,
    },
    {
      lineCode: "31H",
      description: "HURRICANE TAPE (BUNKER IND)",
      lineGroup: 3,
      id: 1516,
    },
    {
      lineCode: "513",
      description: "HURST",
      lineGroup: 4,
      id: 1894,
    },
    {
      lineCode: "98H",
      description: "HUSKY LINERS",
      lineGroup: 4,
      id: 2591,
    },
    {
      lineCode: "281",
      description: "HUTCHINS",
      lineGroup: 2,
      id: 1440,
    },
    {
      lineCode: "72B",
      description: "HUTH PIPE BENDERS",
      lineGroup: 5,
      id: 2202,
    },
    {
      lineCode: "762",
      description: "HYPERTECH",
      lineGroup: 4,
      id: 2267,
    },
    {
      lineCode: "ILK",
      description: "ILINK INDUSTRIES",
      lineGroup: 10,
      id: 2901,
    },
    {
      lineCode: "IND",
      description: "INDUCTION",
      lineGroup: 7,
      id: 2905,
    },
    {
      lineCode: "INN",
      description: "INNOVATIVE TOOLS",
      lineGroup: 2,
      id: 2908,
    },
    {
      lineCode: "IPE",
      description: "IPE FROM JET EQUIPMENT",
      lineGroup: 5,
      id: 334,
    },
    {
      lineCode: "IRN",
      description: "IRON CROSS",
      lineGroup: 4,
      id: 2914,
    },
    {
      lineCode: "IRT",
      description: "IRT",
      lineGroup: 2,
      id: 2915,
    },
    {
      lineCode: "566",
      description: "IRWIN TOOLS",
      lineGroup: 7,
      id: 489,
    },
    {
      lineCode: "44D",
      description: "ISLAND CLEAN AIR",
      lineGroup: 2,
      id: 1781,
    },
    {
      lineCode: "IWA",
      description: "IWATA SPRAY GUNS",
      lineGroup: 2,
      id: 945,
    },
    {
      lineCode: "45J",
      description: "J-B WELD",
      lineGroup: 9,
      id: 1806,
    },
    {
      lineCode: "21U",
      description: "JET AIR TOOLS",
      lineGroup: 7,
      id: 329,
    },
    {
      lineCode: "21T",
      description: "JET TOOL & ABRASIVE",
      lineGroup: 7,
      id: 328,
    },
    {
      lineCode: "21B",
      description: "JET TOOL BOXES",
      lineGroup: 7,
      id: 326,
    },
    {
      lineCode: "0JG",
      description: "JOE GIBBS DRIVEN RACING OIL",
      lineGroup: 6,
      id: 2917,
    },
    {
      lineCode: "666",
      description: "JOHN BEAN CANADA - FMC",
      lineGroup: 5,
      id: 2115,
    },
    {
      lineCode: "341",
      description: "K & N FILTERS",
      lineGroup: 4,
      id: 470,
    },
    {
      lineCode: "421",
      description: "KC HILITES",
      lineGroup: 4,
      id: 1733,
    },
    {
      lineCode: "145",
      description: "KIDDE FIRE EXTINGUISHERS",
      lineGroup: 3,
      id: 1124,
    },
    {
      lineCode: "212",
      description: "KIMBERLY CLARK",
      lineGroup: 3,
      id: 1303,
    },
    {
      lineCode: "KBR",
      description: "KING BEARING",
      lineGroup: 21,
      id: 2919,
    },
    {
      lineCode: "540",
      description: "KING CANADA-GENERATORS",
      lineGroup: 7,
      id: 572,
    },
    {
      lineCode: "539",
      description: "KING CANADA-TOOLS",
      lineGroup: 7,
      id: 571,
    },
    {
      lineCode: "177",
      description: "KLEEN FLO",
      lineGroup: 9,
      id: 840,
    },
    {
      lineCode: "432",
      description: "KRACO",
      lineGroup: 10,
      id: 955,
    },
    {
      lineCode: "KWT",
      description: "KWIK-TEK / SPORSTUF",
      lineGroup: 14,
      id: 630,
    },
    {
      lineCode: "KYB",
      description: "KYB SHOCKS AND STRUTS",
      lineGroup: 24,
      id: 2925,
    },
    {
      lineCode: "178",
      description: "L C CHEMICALS / OSTREM",
      lineGroup: 9,
      id: 1183,
    },
    {
      lineCode: "376",
      description: "LAKEWOOD",
      lineGroup: 4,
      id: 1627,
    },
    {
      lineCode: "35L",
      description: "LAUNCH TECHNOLOGY",
      lineGroup: 5,
      id: 1597,
    },
    {
      lineCode: "LNX",
      description: "LENOX",
      lineGroup: 7,
      id: 2935,
    },
    {
      lineCode: "0LS",
      description: "LIFE SAFE",
      lineGroup: 14,
      id: 2939,
    },
    {
      lineCode: "15E",
      description: "LINCOLN ELECTRIC",
      lineGroup: 5,
      id: 523,
    },
    {
      lineCode: "015",
      description: "LINCOLN LUBE / MITYVAC",
      lineGroup: 5,
      id: 521,
    },
    {
      lineCode: "304",
      description: "LISLE TOOLS",
      lineGroup: 7,
      id: 1490,
    },
    {
      lineCode: "LOC",
      description: "LOCTITE",
      lineGroup: 9,
      id: 2936,
    },
    {
      lineCode: "LAF",
      description: "LORDCO ANTIFREEZE",
      lineGroup: 9,
      id: 434,
    },
    {
      lineCode: "58L",
      description: "LORDCO CYLINDER HEADS",
      lineGroup: 21,
      id: 964,
    },
    {
      lineCode: "66X",
      description: "LORDCO EXTREME HD",
      lineGroup: 1,
      id: 2128,
    },
    {
      lineCode: "0LO",
      description: "LORDCO OIL",
      lineGroup: 6,
      id: 548,
    },
    {
      lineCode: "66R",
      description: "LORDCO ROTORS",
      lineGroup: 1,
      id: 2126,
    },
    {
      lineCode: "61N",
      description: "LORDCO STUFF",
      lineGroup: 9,
      id: 2052,
    },
    {
      lineCode: "043",
      description: "LUBRIMATIC ULTRA LUBE",
      lineGroup: 6,
      id: 788,
    },
    {
      lineCode: "082",
      description: "LUBRIPLATE GREASE",
      lineGroup: 6,
      id: 2362,
    },
    {
      lineCode: "LUC",
      description: "LUCAS CHEMICALS",
      lineGroup: 9,
      id: 579,
    },
    {
      lineCode: "LUO",
      description: "LUCAS OIL",
      lineGroup: 6,
      id: 580,
    },
    {
      lineCode: "644",
      description: "LUFKIN",
      lineGroup: 7,
      id: 340,
    },
    {
      lineCode: "LPS",
      description: "LUK POWER STEERING",
      lineGroup: 24,
      id: 450,
    },
    {
      lineCode: "312",
      description: "LUND TONNEAU COVERS",
      lineGroup: 4,
      id: 531,
    },
    {
      lineCode: "313",
      description: "LUND-EXCEPT TONNEAU COVERS",
      lineGroup: 4,
      id: 532,
    },
    {
      lineCode: "225",
      description: "MAGNACHARGE AUTOMOTIVE BATTERIES",
      lineGroup: 1,
      id: 545,
    },
    {
      lineCode: "25K",
      description: "MAGNAFLOW PERFORMANCE",
      lineGroup: 4,
      id: 1389,
    },
    {
      lineCode: "0MA",
      description: "MAHLE AFTERMARKET",
      lineGroup: 21,
      id: 318,
    },
    {
      lineCode: "169",
      description: "MAHLE ORIGINAL GASKETS",
      lineGroup: 21,
      id: 317,
    },
    {
      lineCode: "108",
      description: "MAHLE RINGS",
      lineGroup: 21,
      id: 315,
    },
    {
      lineCode: "303",
      description: "MAKITA",
      lineGroup: 7,
      id: 1489,
    },
    {
      lineCode: "324",
      description: "MALLORY SQUEEGEE & SCRAPERS",
      lineGroup: 10,
      id: 581,
    },
    {
      lineCode: "MAN",
      description: "MANN-HUMMEL FILTERS",
      lineGroup: 24,
      id: 2967,
    },
    {
      lineCode: "MAR",
      description: "MARADYNE HIGH PERF FANS",
      lineGroup: 4,
      id: 2968,
    },
    {
      lineCode: "46X",
      description: "MARSON RIVETS",
      lineGroup: 7,
      id: 1829,
    },
    {
      lineCode: "500",
      description: "MASTER LOCK",
      lineGroup: 14,
      id: 1880,
    },
    {
      lineCode: "462",
      description: "MCGARD INC.",
      lineGroup: 4,
      id: 1815,
    },
    {
      lineCode: "54M",
      description: "MECHANIX WEAR",
      lineGroup: 4,
      id: 1939,
    },
    {
      lineCode: "486",
      description: "MEGUIARS",
      lineGroup: 2,
      id: 1844,
    },
    {
      lineCode: "978",
      description: "MELLING",
      lineGroup: 21,
      id: 2572,
    },
    {
      lineCode: "MIL",
      description: "MILLER ELECTRIC",
      lineGroup: 5,
      id: 2974,
    },
    {
      lineCode: "479",
      description: "MILWAUKEE TOOL",
      lineGroup: 7,
      id: 583,
    },
    {
      lineCode: "75D",
      description: "MISTER HEATER",
      lineGroup: 14,
      id: 844,
    },
    {
      lineCode: "10K",
      description: "MOBIL 1 OIL",
      lineGroup: 19,
      id: 639,
    },
    {
      lineCode: "090",
      description: "MOLY SLIP",
      lineGroup: 9,
      id: 2476,
    },
    {
      lineCode: "91E",
      description: "MONROE ECONO-MATIC STRUTS",
      lineGroup: 1,
      id: 454,
    },
    {
      lineCode: "91A",
      description: "MONROE QUICK STRUT",
      lineGroup: 1,
      id: 453,
    },
    {
      lineCode: "091",
      description: "MONROE SHOCK",
      lineGroup: 1,
      id: 452,
    },
    {
      lineCode: "092",
      description: "MOOG CHASSIS",
      lineGroup: 1,
      id: 383,
    },
    {
      lineCode: "0MH",
      description: "MOOG HUBS W/KNUCKLES",
      lineGroup: 1,
      id: 387,
    },
    {
      lineCode: "766",
      description: "MOOG U-JOINTS",
      lineGroup: 1,
      id: 382,
    },
    {
      lineCode: "520",
      description: "MOOVIT",
      lineGroup: 9,
      id: 402,
    },
    {
      lineCode: "093",
      description: "MOROSO",
      lineGroup: 4,
      id: 899,
    },
    {
      lineCode: "450",
      description: "MOTHERS WAX",
      lineGroup: 4,
      id: 1792,
    },
    {
      lineCode: "63M",
      description: "MOTORVAC",
      lineGroup: 5,
      id: 2080,
    },
    {
      lineCode: "096",
      description: "MR GASKET",
      lineGroup: 4,
      id: 2549,
    },
    {
      lineCode: "097",
      description: "MSD",
      lineGroup: 4,
      id: 2564,
    },
    {
      lineCode: "MTP",
      description: "MTP INSTRUMENTS",
      lineGroup: 7,
      id: 2980,
    },
    {
      lineCode: "669",
      description: "NATIONAL BEARING",
      lineGroup: 1,
      id: 512,
    },
    {
      lineCode: "529",
      description: "NATIONAL SEAL",
      lineGroup: 1,
      id: 511,
    },
    {
      lineCode: "100",
      description: "NEVER SEEZ",
      lineGroup: 9,
      id: 998,
    },
    {
      lineCode: "NGC",
      description: "NEW GENERATION CLUTCHES",
      lineGroup: 1,
      id: 807,
    },
    {
      lineCode: "NGF",
      description: "NEW GENERATION FLYWHEELS",
      lineGroup: 1,
      id: 808,
    },
    {
      lineCode: "0NG",
      description: "NEW GENERATION HYDRAULICS",
      lineGroup: 1,
      id: 806,
    },
    {
      lineCode: "11O",
      description: "NGK (NTK) OXYGEN SENSORS",
      lineGroup: 1,
      id: 492,
    },
    {
      lineCode: "101",
      description: "NGK SPARK PLUGS",
      lineGroup: 1,
      id: 491,
    },
    {
      lineCode: "638",
      description: "NGK WIRES",
      lineGroup: 1,
      id: 493,
    },
    {
      lineCode: "744",
      description: "NICHOLSON FILES",
      lineGroup: 7,
      id: 341,
    },
    {
      lineCode: "664",
      description: "NLS/FLUID FILM",
      lineGroup: 9,
      id: 2113,
    },
    {
      lineCode: "564",
      description: "NO TOUCH TIRE CARE",
      lineGroup: 9,
      id: 711,
    },
    {
      lineCode: "29N",
      description: "NORTHERN PERF RADIATORS",
      lineGroup: 4,
      id: 1467,
    },
    {
      lineCode: "348",
      description: "NOS",
      lineGroup: 4,
      id: 1567,
    },
    {
      lineCode: "119",
      description: "NUVUE (POWERFLOW)",
      lineGroup: 10,
      id: 1046,
    },
    {
      lineCode: "OTD",
      description: "O T C  DIAGNOSTICS",
      lineGroup: 5,
      id: 460,
    },
    {
      lineCode: "OTC",
      description: "O T C  TOOLS",
      lineGroup: 7,
      id: 459,
    },
    {
      lineCode: "OPT",
      description: "OPTIMA BATTERIES",
      lineGroup: 4,
      id: 983,
    },
    {
      lineCode: "OFB",
      description: "OUTLAND FIRE BOWL",
      lineGroup: 14,
      id: 2990,
    },
    {
      lineCode: "105",
      description: "PAPCO",
      lineGroup: 3,
      id: 984,
    },
    {
      lineCode: "PEK",
      description: "PEEK CHEMICALS",
      lineGroup: 9,
      id: 3028,
    },
    {
      lineCode: "545",
      description: "PENNZOIL",
      lineGroup: 6,
      id: 816,
    },
    {
      lineCode: "PFL",
      description: "PENTOSIN FLUIDS",
      lineGroup: 24,
      id: 515,
    },
    {
      lineCode: "PFO",
      description: "PENTOSIN OIL",
      lineGroup: 24,
      id: 516,
    },
    {
      lineCode: "51P",
      description: "PERFORMANCE RACING WAREHOUSE",
      lineGroup: 21,
      id: 1906,
    },
    {
      lineCode: "110",
      description: "PERMATEX",
      lineGroup: 9,
      id: 709,
    },
    {
      lineCode: "PHI",
      description: "PHILIPS LIGHTING",
      lineGroup: 1,
      id: 3031,
    },
    {
      lineCode: "75P",
      description: "PIAA LIGHTING",
      lineGroup: 4,
      id: 494,
    },
    {
      lineCode: "75Z",
      description: "PIAA POWERSPORTS",
      lineGroup: 4,
      id: 496,
    },
    {
      lineCode: "75W",
      description: "PIAA WIPERS",
      lineGroup: 4,
      id: 495,
    },
    {
      lineCode: "113",
      description: "PICO",
      lineGroup: 1,
      id: 1041,
    },
    {
      lineCode: "114",
      description: "PIONEER ENGINE PRODUCTS",
      lineGroup: 21,
      id: 1042,
    },
    {
      lineCode: "42P",
      description: "PIONEER SAFETY PRODUCTS",
      lineGroup: 7,
      id: 330,
    },
    {
      lineCode: "0PD",
      description: "PLASTI DIP",
      lineGroup: 2,
      id: 3026,
    },
    {
      lineCode: "116",
      description: "PLASTI-KOTE PAINT",
      lineGroup: 2,
      id: 613,
    },
    {
      lineCode: "038",
      description: "PLASTICOLOR",
      lineGroup: 4,
      id: 988,
    },
    {
      lineCode: "535",
      description: "PLEWS",
      lineGroup: 7,
      id: 790,
    },
    {
      lineCode: "0PL",
      description: "POP & LOCK",
      lineGroup: 4,
      id: 3033,
    },
    {
      lineCode: "POR",
      description: "POR-15",
      lineGroup: 2,
      id: 3035,
    },
    {
      lineCode: "0PB",
      description: "POWER BOND",
      lineGroup: 21,
      id: 693,
    },
    {
      lineCode: "12P",
      description: "POWERMASTER MOTORSPORTS",
      lineGroup: 4,
      id: 992,
    },
    {
      lineCode: "EDG",
      description: "POWERTEQ",
      lineGroup: 4,
      id: 501,
    },
    {
      lineCode: "0SC",
      description: "POWERTEQ",
      lineGroup: 4,
      id: 502,
    },
    {
      lineCode: "PRA",
      description: "PRAXAIR GAS",
      lineGroup: 8,
      id: 497,
    },
    {
      lineCode: "PRW",
      description: "PRAXAIR WELDING - NOT GAS",
      lineGroup: 8,
      id: 499,
    },
    {
      lineCode: "567",
      description: "PRESTONE",
      lineGroup: 9,
      id: 1958,
    },
    {
      lineCode: "PRE",
      description: "PREVOST",
      lineGroup: 2,
      id: 3037,
    },
    {
      lineCode: "278",
      description: "PRO FORM BODY SUPPLIES",
      lineGroup: 2,
      id: 996,
    },
    {
      lineCode: "61P",
      description: "PRO SPOT WELDING",
      lineGroup: 8,
      id: 2053,
    },
    {
      lineCode: "860",
      description: "PRO-TEK AUTO BODY TOOLS",
      lineGroup: 2,
      id: 2420,
    },
    {
      lineCode: "55M",
      description: "PRO-WASH/CUDA/MANCORP",
      lineGroup: 5,
      id: 1954,
    },
    {
      lineCode: "PCS",
      description: "PROCAR SEAT",
      lineGroup: 4,
      id: 507,
    },
    {
      lineCode: "390",
      description: "PROFORM PERFORMANCE PRODUCTS",
      lineGroup: 4,
      id: 1657,
    },
    {
      lineCode: "76P",
      description: "PUTCO",
      lineGroup: 4,
      id: 2282,
    },
    {
      lineCode: "267",
      description: "QUAKER STATE",
      lineGroup: 6,
      id: 815,
    },
    {
      lineCode: "21C",
      description: "QUALITY CHAIN",
      lineGroup: 3,
      id: 1309,
    },
    {
      lineCode: "688",
      description: "QUICK CABLE / AMI BATT CLMP",
      lineGroup: 14,
      id: 2143,
    },
    {
      lineCode: "QFT",
      description: "QUICK FUEL TECHNOLOGY",
      lineGroup: 4,
      id: 3043,
    },
    {
      lineCode: "0RQ",
      description: "RACEQUIP",
      lineGroup: 4,
      id: 3076,
    },
    {
      lineCode: "21A",
      description: "RACOR FILTERS / ADP DISTRIBUTORS",
      lineGroup: 1,
      id: 864,
    },
    {
      lineCode: "870",
      description: "RAIN-X",
      lineGroup: 9,
      id: 714,
    },
    {
      lineCode: "665",
      description: "RANCHO",
      lineGroup: 4,
      id: 2114,
    },
    {
      lineCode: "0RF",
      description: "RAPID FIX",
      lineGroup: 9,
      id: 3061,
    },
    {
      lineCode: "164",
      description: "RAYBESTOS BRAKE HYDRAULICS",
      lineGroup: 1,
      id: 409,
    },
    {
      lineCode: "963",
      description: "RAYBESTOS FRICTION",
      lineGroup: 1,
      id: 410,
    },
    {
      lineCode: "322",
      description: "RAYOVAC",
      lineGroup: 10,
      id: 1526,
    },
    {
      lineCode: "71R",
      description: "RBL PRODUCTS",
      lineGroup: 2,
      id: 2194,
    },
    {
      lineCode: "451",
      description: "RCI/RACERS CHOICE INC",
      lineGroup: 4,
      id: 1793,
    },
    {
      lineCode: "RLS",
      description: "READYLIFT SUSPENSION",
      lineGroup: 4,
      id: 587,
    },
    {
      lineCode: "256",
      description: "RECOCHEM CHEMICALS",
      lineGroup: 9,
      id: 431,
    },
    {
      lineCode: "356",
      description: "RECOCHEM GUN WASH",
      lineGroup: 2,
      id: 432,
    },
    {
      lineCode: "125",
      description: "RECORD VICES",
      lineGroup: 7,
      id: 488,
    },
    {
      lineCode: "RLO",
      description: "RED LINE OIL",
      lineGroup: 6,
      id: 3068,
    },
    {
      lineCode: "RTR",
      description: "RED TEK REFRIGERANT",
      lineGroup: 9,
      id: 3079,
    },
    {
      lineCode: "RCH",
      description: "REIN COOLANT HOSES",
      lineGroup: 24,
      id: 435,
    },
    {
      lineCode: "RFA",
      description: "REIN FIRST AID",
      lineGroup: 24,
      id: 437,
    },
    {
      lineCode: "RMT",
      description: "REIN MOUNTS",
      lineGroup: 24,
      id: 438,
    },
    {
      lineCode: "54R",
      description: "REMFLEX EXHAUST GASKETS",
      lineGroup: 4,
      id: 1941,
    },
    {
      lineCode: "10J",
      description: "RESTORE",
      lineGroup: 9,
      id: 1031,
    },
    {
      lineCode: "RIS",
      description: "RISLONE",
      lineGroup: 9,
      id: 3064,
    },
    {
      lineCode: "699",
      description: "ROBINAIR",
      lineGroup: 5,
      id: 509,
    },
    {
      lineCode: "50R",
      description: "ROCK TAMERS",
      lineGroup: 14,
      id: 888,
    },
    {
      lineCode: "678",
      description: "ROTARY LIFTS",
      lineGroup: 5,
      id: 2132,
    },
    {
      lineCode: "21Z",
      description: "ROTOMASTER TURBOS & MISC",
      lineGroup: 21,
      id: 865,
    },
    {
      lineCode: "ROY",
      description: "ROYAL PURPLE",
      lineGroup: 4,
      id: 3073,
    },
    {
      lineCode: "0RL",
      description: "RUGGED LINER",
      lineGroup: 4,
      id: 3065,
    },
    {
      lineCode: "517",
      description: "RUSSELL PERFORMANCE",
      lineGroup: 4,
      id: 826,
    },
    {
      lineCode: "770",
      description: "S T P",
      lineGroup: 9,
      id: 810,
    },
    {
      lineCode: "93S",
      description: "SAMLEX INVERTERS",
      lineGroup: 14,
      id: 2525,
    },
    {
      lineCode: "752",
      description: "SATA SPRAY EQUIPMENT",
      lineGroup: 2,
      id: 2253,
    },
    {
      lineCode: "42S",
      description: "SCAT CRANKSHAFT",
      lineGroup: 21,
      id: 506,
    },
    {
      lineCode: "133",
      description: "SCEPTER JERRY CANS",
      lineGroup: 10,
      id: 1093,
    },
    {
      lineCode: "88S",
      description: "SCHUMACHER BATTERY CHARGERS",
      lineGroup: 7,
      id: 2456,
    },
    {
      lineCode: "935",
      description: "SCN INDUSTRIAL",
      lineGroup: 8,
      id: 592,
    },
    {
      lineCode: "0SF",
      description: "SEA FOAM",
      lineGroup: 9,
      id: 3127,
    },
    {
      lineCode: "162",
      description: "SEALED POWER ENGINE PARTS",
      lineGroup: 21,
      id: 647,
    },
    {
      lineCode: "03S",
      description: "SEATTLE TOOL",
      lineGroup: 7,
      id: 796,
    },
    {
      lineCode: "423",
      description: "SECURITY CHAIN (KITO)",
      lineGroup: 10,
      id: 1735,
    },
    {
      lineCode: "430",
      description: "SEM",
      lineGroup: 2,
      id: 1754,
    },
    {
      lineCode: "0SW",
      description: "SHARK WELDING",
      lineGroup: 8,
      id: 3152,
    },
    {
      lineCode: "SHL",
      description: "SHELL OIL",
      lineGroup: 6,
      id: 817,
    },
    {
      lineCode: "761",
      description: "SHOP-VAC",
      lineGroup: 7,
      id: 2266,
    },
    {
      lineCode: "446",
      description: "SILV-O-LITE PISTONS",
      lineGroup: 21,
      id: 603,
    },
    {
      lineCode: "SIR",
      description: "SIRIUS RADIO",
      lineGroup: 10,
      id: 721,
    },
    {
      lineCode: "017",
      description: "SKF BEARINGS",
      lineGroup: 1,
      id: 503,
    },
    {
      lineCode: "048",
      description: "SKF SEALS",
      lineGroup: 1,
      id: 505,
    },
    {
      lineCode: "SKY",
      description: "SKYJACKER SUSPENSION",
      lineGroup: 4,
      id: 3134,
    },
    {
      lineCode: "SLI",
      description: "SLIME BY PERMATEX",
      lineGroup: 9,
      id: 715,
    },
    {
      lineCode: "81S",
      description: "SMC PNEUMATIC",
      lineGroup: 5,
      id: 2361,
    },
    {
      lineCode: "143",
      description: "SNAPPI-HOOKERS",
      lineGroup: 10,
      id: 1123,
    },
    {
      lineCode: "0SB",
      description: "SNOWBEAR",
      lineGroup: 14,
      id: 3124,
    },
    {
      lineCode: "204",
      description: "SOLDER SEAL GUNK",
      lineGroup: 9,
      id: 1284,
    },
    {
      lineCode: "S70",
      description: "SP TOOLS - EQUIPMENT",
      lineGroup: 5,
      id: 593,
    },
    {
      lineCode: "S80",
      description: "SP TOOLS - TOOLS",
      lineGroup: 7,
      id: 594,
    },
    {
      lineCode: "577",
      description: "SPECIALTY PRODUCTS",
      lineGroup: 7,
      id: 1973,
    },
    {
      lineCode: "85A",
      description: "SPI AIR CONDITIONING",
      lineGroup: 1,
      id: 266,
    },
    {
      lineCode: "85F",
      description: "SPI FUEL PUMPS / SENDERS",
      lineGroup: 1,
      id: 270,
    },
    {
      lineCode: "85S",
      description: "SPI GAS TANKS",
      lineGroup: 1,
      id: 276,
    },
    {
      lineCode: "85H",
      description: "SPI HEATER CORES",
      lineGroup: 1,
      id: 271,
    },
    {
      lineCode: "85R",
      description: "SPI RADIATORS",
      lineGroup: 1,
      id: 275,
    },
    {
      lineCode: "96S",
      description: "SPORT RACK",
      lineGroup: 14,
      id: 1011,
    },
    {
      lineCode: "572",
      description: "SPRAY NINE",
      lineGroup: 9,
      id: 712,
    },
    {
      lineCode: "SMX",
      description: "SPRAYMAX",
      lineGroup: 2,
      id: 596,
    },
    {
      lineCode: "SSB",
      description: "STAINLESS STEEL BRAKE CORP",
      lineGroup: 4,
      id: 597,
    },
    {
      lineCode: "STA",
      description: "STANADYNE",
      lineGroup: 1,
      id: 885,
    },
    {
      lineCode: "148",
      description: "STANT",
      lineGroup: 1,
      id: 694,
    },
    {
      lineCode: "97S",
      description: "STAR WARNING SYSTEMS",
      lineGroup: 10,
      id: 2579,
    },
    {
      lineCode: "24S",
      description: "STECK PRODUCTS",
      lineGroup: 2,
      id: 1373,
    },
    {
      lineCode: "966",
      description: "STEINEL HEAT GUNS",
      lineGroup: 2,
      id: 2551,
    },
    {
      lineCode: "530",
      description: "STEWART WARNER",
      lineGroup: 10,
      id: 1924,
    },
    {
      lineCode: "722",
      description: "STOCKHAUSEN / STOKO SKIN CARE",
      lineGroup: 2,
      id: 748,
    },
    {
      lineCode: "87S",
      description: "STOPTECH",
      lineGroup: 4,
      id: 540,
    },
    {
      lineCode: "745",
      description: "STRONGARM JACKS",
      lineGroup: 7,
      id: 332,
    },
    {
      lineCode: "0SA",
      description: "STRONGARM LIFT SUPPORTS",
      lineGroup: 1,
      id: 3121,
    },
    {
      lineCode: "SDE",
      description: "SUNDOG EYEWEAR",
      lineGroup: 10,
      id: 3126,
    },
    {
      lineCode: "579",
      description: "SUPEREX",
      lineGroup: 10,
      id: 1974,
    },
    {
      lineCode: "17S",
      description: "SUPERSPRINGS",
      lineGroup: 14,
      id: 1200,
    },
    {
      lineCode: "SCG",
      description: "SURF CITY GARAGE",
      lineGroup: 4,
      id: 3125,
    },
    {
      lineCode: "80S",
      description: "SUSPENSION TECHNIQUES",
      lineGroup: 4,
      id: 775,
    },
    {
      lineCode: "SYM",
      description: "SYMTECH & BRIGHT SOLUTIONS",
      lineGroup: 5,
      id: 3153,
    },
    {
      lineCode: "620",
      description: "TAYLOR WIRES",
      lineGroup: 4,
      id: 599,
    },
    {
      lineCode: "77T",
      description: "TCA TOOL STORAGE",
      lineGroup: 7,
      id: 2301,
    },
    {
      lineCode: "525",
      description: "TEMRO",
      lineGroup: 1,
      id: 1911,
    },
    {
      lineCode: "THG",
      description: "THE HOFFMAN GROUP",
      lineGroup: 4,
      id: 3179,
    },
    {
      lineCode: "851",
      description: "THULE CAR + BIKE RACKS",
      lineGroup: 4,
      id: 1010,
    },
    {
      lineCode: "TIM",
      description: "TIMBREN SES KITS",
      lineGroup: 14,
      id: 3183,
    },
    {
      lineCode: "TFT",
      description: "TITAN FUEL TANKS",
      lineGroup: 4,
      id: 3177,
    },
    {
      lineCode: "0TT",
      description: "TITAN TIRE",
      lineGroup: 14,
      id: 3195,
    },
    {
      lineCode: "97T",
      description: "TOOL CACHE",
      lineGroup: 7,
      id: 562,
    },
    {
      lineCode: "518",
      description: "TRANSDAPT/HAMBURGER'S",
      lineGroup: 4,
      id: 1012,
    },
    {
      lineCode: "850",
      description: "TRI-FLOW",
      lineGroup: 9,
      id: 756,
    },
    {
      lineCode: "241",
      description: "TRICO WIPER BLADES",
      lineGroup: 1,
      id: 1356,
    },
    {
      lineCode: "154",
      description: "TRIDON HOSE CLAMPS",
      lineGroup: 1,
      id: 696,
    },
    {
      lineCode: "TRI",
      description: "TRIMAX",
      lineGroup: 14,
      id: 3192,
    },
    {
      lineCode: "TRX",
      description: "TRUXEDO",
      lineGroup: 4,
      id: 602,
    },
    {
      lineCode: "163",
      description: "TURTLE WAX",
      lineGroup: 9,
      id: 1162,
    },
    {
      lineCode: "47F",
      description: "TUTHILL / FILL-RITE",
      lineGroup: 3,
      id: 1836,
    },
    {
      lineCode: "UVW",
      description: "U VIEW CONSUMABLES",
      lineGroup: 5,
      id: 909,
    },
    {
      lineCode: "UND",
      description: "UNDERCOVER TRUCK BED COVERS",
      lineGroup: 4,
      id: 605,
    },
    {
      lineCode: "967",
      description: "UNI-RAM",
      lineGroup: 2,
      id: 2552,
    },
    {
      lineCode: "0VB",
      description: "VALLEY BRUSH",
      lineGroup: 3,
      id: 3204,
    },
    {
      lineCode: "940",
      description: "VANGUARD STEEL",
      lineGroup: 3,
      id: 611,
    },
    {
      lineCode: "VGW",
      description: "VANGUARD WELDING",
      lineGroup: 8,
      id: 612,
    },
    {
      lineCode: "168",
      description: "VHT PAINT",
      lineGroup: 4,
      id: 754,
    },
    {
      lineCode: "VIA",
      description: "VIAIR / WURTON",
      lineGroup: 4,
      id: 3208,
    },
    {
      lineCode: "VIB",
      description: "VIBRANT PERFORMANCE",
      lineGroup: 4,
      id: 3209,
    },
    {
      lineCode: "60T",
      description: "VICTOR TECHNOLOGIES",
      lineGroup: 8,
      id: 2037,
    },
    {
      lineCode: "VMS",
      description: "VISION MOTOR SPORTS",
      lineGroup: 4,
      id: 3210,
    },
    {
      lineCode: "0WF",
      description: "WAGNER FRICTION",
      lineGroup: 1,
      id: 513,
    },
    {
      lineCode: "171",
      description: "WALKER EXHAUST",
      lineGroup: 1,
      id: 623,
    },
    {
      lineCode: "895",
      description: "WALTER GRINDING DISCS",
      lineGroup: 3,
      id: 2461,
    },
    {
      lineCode: "985",
      description: "WARN HUBS & WINCHES",
      lineGroup: 4,
      id: 550,
    },
    {
      lineCode: "002",
      description: "WATSON GLOVE & RAINGEAR",
      lineGroup: 3,
      id: 1280,
    },
    {
      lineCode: "173",
      description: "WD-40",
      lineGroup: 9,
      id: 1181,
    },
    {
      lineCode: "0WT",
      description: "WEATHER TECH",
      lineGroup: 4,
      id: 3238,
    },
    {
      lineCode: "86W",
      description: "WEDGE CLAMP",
      lineGroup: 2,
      id: 622,
    },
    {
      lineCode: "960",
      description: "WEIAND",
      lineGroup: 4,
      id: 2550,
    },
    {
      lineCode: "527",
      description: "WELLER PROPANE & SOLDER",
      lineGroup: 7,
      id: 339,
    },
    {
      lineCode: "751",
      description: "WESTERN MARINE",
      lineGroup: 14,
      id: 629,
    },
    {
      lineCode: "WRD",
      description: "WHISTLER RADAR DETECTORS",
      lineGroup: 10,
      id: 3235,
    },
    {
      lineCode: "945",
      description: "WILMAR - PERFORMANCE TOOL",
      lineGroup: 7,
      id: 627,
    },
    {
      lineCode: "946",
      description: "WILMAR BULK",
      lineGroup: 7,
      id: 628,
    },
    {
      lineCode: "201",
      description: "WILSON REMAN ELECTRICAL",
      lineGroup: 1,
      id: 619,
    },
    {
      lineCode: "944",
      description: "WISS SNIPS",
      lineGroup: 7,
      id: 342,
    },
    {
      lineCode: "WSH",
      description: "WORKSHOP HERO",
      lineGroup: 2,
      id: 3236,
    },
    {
      lineCode: "YGA",
      description: "YUKON GEAR & AXLE",
      lineGroup: 1,
      id: 3246,
    },
    {
      lineCode: "95Z",
      description: "ZORBOLITE OIL ABSORBENT",
      lineGroup: 9,
      id: 1020,
    },
  ],
  majorCategories: [
    {
      id: 19,
      groupDesc_tradeshow: "AC Delco",
    },
    {
      id: 10,
      groupDesc_tradeshow: "Auto Accessories",
    },
    {
      id: 1,
      groupDesc_tradeshow: "Automotive",
    },
    {
      id: 22,
      groupDesc_tradeshow: "Beck Arnley",
    },
    {
      id: 2,
      groupDesc_tradeshow: "Body Shop",
    },
    {
      id: 9,
      groupDesc_tradeshow: "Chemicals",
    },
    {
      id: 21,
      groupDesc_tradeshow: "Engine",
    },
    {
      id: 5,
      groupDesc_tradeshow: "Equipment",
    },
    {
      id: 4,
      groupDesc_tradeshow: "High Performance",
    },
    {
      id: 24,
      groupDesc_tradeshow: "Import Parts",
    },
    {
      id: 3,
      groupDesc_tradeshow: "Industrial Supplies",
    },
    {
      id: 6,
      groupDesc_tradeshow: "Oil Products",
    },
    {
      id: 14,
      groupDesc_tradeshow: "RV and Marine",
    },
    {
      id: 7,
      groupDesc_tradeshow: "Tools",
    },
    {
      id: 8,
      groupDesc_tradeshow: "Welding and Gas",
    },
  ],
};

mock.onGet("/api/tradeshow/majorCategories").reply((config) => {
  return [200, tradeshowDB.majorCategories];
});

mock.onGet("/api/tradeshow/majorCategory_lineCodes").reply((config) => {
  return [200, tradeshowDB.majorCategory_lineCodes];
});
